version: '3.8'

services:
  admin_db:
    image: postgres:latest
    container_name: user
    ports:
      - "8001:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: psw