server:
  port: 9071
spring:
  cache:
    redis:
      time-to-live: 60000
  datasource:
    username: admin
    password: psw
    url: jdbc:postgresql://localhost:8001/user
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        ddl-auto: validate
        format_sql: true
  liquibase:
    change-log: classpath:db.changelog/changelog-user.yml
jwt:
  secret: "sai'jfdslkgo32941;'';slg`0ws;'0sqa;"
  tokenExpire: 6000
  refreshTokenExpire: 7
password:
  encode:
    strength: ${STRENGTH:-1}